### ISSUE TITLE
documentations about the library

### ISSUE THREAD

**Issue by roozbeh63** [convertersystems/opc-ua-samples#13]
where I can find more documentations about using this library, your example are already good, but I need a proper documentations to review. 
thanks

**Comment by awcullen** [comment]
There is no documentation for this library yet.
You may find the [specifications](https://opcfoundation.org/developer-tools/specifications-unified-architecture) of OPC UA interesting. I tried to follow these as best I could.

**Comment by roozbeh63** [comment]
if it is not too much to ask and you have time, can you please create a windows form example of your library? with simple functions, just a simple read and write values to some nodes. 
much thanks in advance

**Comment by awcullen** [comment]
Sorry, we won't be supporting WinForms.
