### ISSUE TITLE
MobileHmi.Uwp ?

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-samples#14]
Would be possible to get the MobileHmi sample working also on UWP ?
As I did not use UrhoSharp by now, could you please tell me what tools are you using to design the UrhoSharp 3D graphical objects ?

**Comment by awcullen** [comment]
I think it would be quite possible to have the MobileHmi sample working on UWP and iOS. It's just a matter of time.

Regarding the 3d assets for UrhoSharp, I used the open-source tool 'Blender' as well as the add-in 'Blender to Urho Exporter'.

**Comment by abrasat** [comment]
Thanks for the information.
Is it possible to bind the node identifier string (the attribute from the view model element) to a graphic item (for instance a label) ?

**Comment by awcullen** [comment]
Sorry there no support in XAML for binding to Attributes

**Comment by tejasklodha** [comment]
Hi awcullen,

Are U used https://github.com/reattiva/Urho3D-Blender ?

**Comment by awcullen** [comment]
Yes, thanks for finding the link. I corrected my previous comment.

**Comment by abrasat** [comment]
I know that it is not directly related to opc-ua, but do you know if it is possible also to import UrhoSharp 3d assets back to Blender, in view to edit them ? Or how do you modify them ?
Can you recommend some good sites with 3d models for Blender/UrhoSharp ?

**Comment by awcullen** [comment]
I don't know of a way to get the Urho3d scene assets back into Blender. 
Google is a good tool to find 3d models. Blender imports so many formats.

**Comment by abrasat** [comment]
In the MobileHmi sample the Fps is limited by setting the MinFps and MaxFps engine parameters. How can the current Fps be determined ?
