### ISSUE TITLE
two way communications possible in this example?

### ISSUE THREAD

**Issue by tejasklodha** [convertersystems/opc-ua-samples#18]
Hi,

Can we do two way communication between Mobile app(Mobil Hmi) to OPC server?
Can you demonstrate in exiting example?
Example: i want give parameters to axis by mobile app n axis changed on given parameters.
Or
I want to stop machine by mobile app,
Or
I want to start again machine by mobile app?

**Comment by awcullen** [comment]
Yes, two way communications is possible.
In the sample [MobileHmi.Droid](https://github.com/convertersystems/opc-ua-samples/tree/master/MobileHmi.Droid), if the sample NodeServer is also running, then you can change the robot Mode to 'Hand' and then adjust the sliders to write the Axis values to the server.

**Comment by tejasklodha** [comment]
Thanks... 👍
