### ISSUE TITLE
Why are you rewrite the OPC Server code with Node.js

### ISSUE THREAD

**Issue by ggokka** [convertersystems/opc-ua-samples#2]
What is the benefits of the node-opcua compared with the OPC Foundation SDK?

**Comment by awcullen** [comment]
The reasons are:
1. I found the foundation's server api overly complicated for my simple needs.
2. The foundation's license is not really compatible with MIT.
3. The foundation's codes _were_ not portable to other platforms, for example Rasberry Pi. (That is being corrected by https://github.com/OPCFoundation/UA-.NETStandardLibrary)
