### ISSUE TITLE
Mobile Hmi sample on Hololens ?

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-samples#22]
What code changes would be necessary in view to adapt the MobileHmi Urho-based sample, to get it running also on a HoloLens device (UrhoSharp should actually support also HoloLens )?

**Comment by awcullen** [comment]
I have heard that Workstation.UaClient works on HoloLens devices. I don't know if UrhoSharp does. Maybe you should ask the Xamarin folks.

**Comment by awcullen** [comment]
UrhoSharp has a HoloLens package and a sample here:
https://github.com/xamarin/urho-samples/tree/master/HoloLens
