### ISSUE TITLE
Fetch data to mobile from Cloud

### ISSUE THREAD

**Issue by tejasklodha** [convertersystems/opc-ua-samples#25]
Dear Sir,

Its not issue but want suggestion.
I want to use mobile application MobileHmi from any where through internet.

because MobileHmi.Droid only run in intranet(in the same network) but how we can use this application in internet?

Any OPC UA web service required? 

Thanks.

**Comment by awcullen** [comment]
Now, you could open your opc ua server to the internet (with security turned on, I hope). The current protocol was designed for speed (binary) and security (encryption) when communicating with servers over the internet.

I am anticipating the release of opc ua servers that support the PubSub api. With this new extension to the protocol, you can use a cloud service to be the intermediary between a client and server. 

As a solution for today, I have been hearing good things about https://thingsboard.io/

**Comment by tejasklodha** [comment]
Thanks awcullen for giving information.. I will look that....
Also start working in azure with OPC....

**Comment by tejasklodha** [comment]
Dear Sir,

I found some interesting information about OPC UA on internet.

https://github.com/node-opcua/node-opcua/wiki/publicly-available-OPCUA-servers
