### ISSUE TITLE
Can we send live data dump to Sql Server from PLC

### ISSUE THREAD

**Issue by tejasklodha** [convertersystems/opc-ua-samples#28]
Dear Sir,

It is not issue but enhancement.

Can you demonstrate that live variable of data from PLC to send Local sql server (Same network) and store in database?

Thanks,

**Comment by tejasklodha** [comment]
Dear Sir,

Its really very helpful to us if you Can demonstrate this..

Thanks,

**Comment by awcullen** [comment]
I do plan to add this feature to the DataLogger sample.

In the meantime, I am fascinated with the open source project [https://thingsboard.io/](https://thingsboard.io/).

I think you have tried Azure IOT, correct?

Well, Thingsboard is similar, in that it collects IOT data, stores in database, has server functions, and dashboard-style web hmi. In addition, it can run in cloud -or- completely within your office / factory. 
In my office, I have a Kepware OPC UA server providing simulated data. A service 'tb-gateway', creates subscription and forwards the data to 'thingsboard' service via MQTT. 'Thingsboard' service stores in a database and updates any web connected dashboard hmi's. Try for yourself.

**Comment by tejasklodha** [comment]
Dear sir,

Sounds good to listen that you are planning to add this feature :).... 

Yup I already tried azure iot but first main requirement is store opc ua data in local database only(no cloud).... Just add your comments when you completed...

and right now i take reference of your code and start working to make new wpf application which store opc ua server data in local sql server database​ but I will also explore to thingsboard.io.......

Thanks.

**Comment by tejasklodha** [comment]
Done...
