### ISSUE TITLE
Timing at application startup

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-samples#29]
The following problem occurs at startup if a opc-ua item has a constant value. The view model (containing the MonitoredItem attribute) is initialized and the monitored opc-ua item fetched, before the Urho object is created. The "Renderer" property is set only after the view model already received the opc-ua item value ( I tested with the debugger). This leads to the problem that the bindable property changes before the urho object was showed, and practically the urho code "misses" the property change.

` 
  protected async override void OnPropertyChanged([CallerMemberName] string propertyName = null)
  {
              base.OnPropertyChanged(propertyName);
              if (propertyName == "Renderer")
              {
                  this.robotGame = await this.UrhoSurface.Show<RobotGame>(new 
  ApplicationOptions(assetsFolder: "Data") { Orientation = 
  ApplicationOptions.OrientationType.LandscapeAndPortrait });
             }
         }
`

How could the startup order be changed, to avoid the problems that occur if a opc-ua item has a constant value ? (sorry, I cannot get the code formatted properly...)

**Comment by awcullen** [comment]
Thanks for reporting this issue. I've fixed the samples to use the initial values.
