### ISSUE TITLE
OPC UA Example of website

### ISSUE THREAD

**Issue by tejasklodha** [convertersystems/opc-ua-samples#34]
Dear Sir,

**It is not issue but only suggestions...**

`I am Very Happy to use and learn about OPC UA on your repository ... `

All type of example available in your repository **except Website.** 
I think you also give some basic example that how we can see live data efficiently of OPC UA on Web...

Are you plan something like that?

Thanks,

**Comment by awcullen** [comment]
I have not considered a cloud based service or a webclient. 
There are two projects I am watching in this category.

https://mva.microsoft.com/en-US/training-courses/introduction-to-azure-iot-17611

https://thingsboard.io/

**Comment by tejasklodha** [comment]
Dear Sir,

Thanks for provide a links....

But I already successfully send OPC UA server data to azure portal and also show live data on web portal which is host on azure....
But disadvantage of cloud is that we pay for it even if We want to monitor data on **same network**...

**And beauty of you all applications is that we can able to use without cost If it is in same network....** So I Found Example of webapplication which is same network(Web site host on internal server)

Thanks,

**Comment by abrasat** [comment]
Does the thingsboard platform allow also to write values to opc-ua nodes, or is just read access ?

**Comment by awcullen** [comment]
Today the OpcUa nodes are readonly. They say writing to nodes is planned for next version.

**Comment by abrasat** [comment]
Ok, thanks. Could you get it working with the RobotServer from the opc-ua samples ?

**Comment by Savoyyang** [comment]
I also want to know @awcullen
