### ISSUE TITLE
Build action ‘EmbeddedResource’ is not supported by one or more of the project’s targets

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-samples#4]
When trying to load the "opc-ua-samples" solution in Visual Studio 2015, the above error occurs for the project Workstation.MobileHmi (Portable), with the file MainPage.xaml.
What could be the cause ?

**Comment by awcullen** [comment]
This error also affects other Xamarin Forms samples, and has been reported to Xamarin.
For me, the project still compiles and runs.

**Comment by awcullen** [comment]
I switch the project Workstation.MobileHmi (Portable) from PCL to Shared. The error 'Build action ‘EmbeddedResource’ is not supported by one or more of the project’s targets' was removed.

**Comment by Ghebrehiywet** [comment]
open solution on VS with administrator mode and rebuild each one by one.
