### ISSUE TITLE
How does the initial reconnect work?

### ISSUE THREAD

**Issue by ggokka** [convertersystems/opc-ua-samples#42]
As if the client start before the server doesn't start.
This code works well this condition.
What is the machinism?

            this.application = new UaApplicationBuilder()
                .SetApplicationUri($"urn:{Dns.GetHostName()}:Workstation.RobotHmi")
                .SetDirectoryStore(Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                    "Workstation.RobotHmi",
                    "pki"))
                .SetIdentity(this.ShowSignInDialog)
                .SetLoggerFactory(this.loggerFactory)
                .AddMappedEndpoints(config)
                .Build();

**Comment by awcullen** [comment]
Its really quite simplistic.  When a subscription requests a channel to an endpoint, a new UaTcpSessionChannel is created and opened.  If the open is not successful, the channel is disposed and a new channel is created after 2 seconds delay.
