### ISSUE TITLE
Workstation.RobotApp Exception in Windows.UI.Xaml.dll code 0xc000027b

### ISSUE THREAD

**Issue by katdti** [convertersystems/opc-ua-samples#43]
Have compiled Workstation.RobotApp and it run berfekt on my developer PC.
Have copied and installed it on a Win 10 Surface PC - here it crashes with:

Faulting module name: Windows.UI.Xaml.dll, version: 10.0.15063.966, time stamp: 0xe9d547ca
Exception code: 0xc000027b

Tried to remote debug. First it failed with unable to load mon-urho.dll becuase project is missing refrence to c++ runtime as described here:
   https://stackoverflow.com/questions/39894134/urhosharp-forms-on-uwp-unable-to-load-dll-mono-urho?noredirect=1&lq=1
Adding the refenrce I can remote debug the App on the Surface PC - and the App runs perfect.
Installing it again and lunching it I get same Windows.UI.Xaml.dll error again.

It run in remote debugger but not when installed side loaded.

**Comment by awcullen** [comment]
I don't know how to help with this issue.  Please reopen if you are still having problem.
