### ISSUE TITLE
Workstation.MobileHmi.Droid project compilation errors

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-samples#7]
I am trying to compile the new version but am getting lots of errors like:

...
Please install package: 'Xamarin.Android.Support.v7.CardView' available in SDK installer. Android resource directory C:\Users\***\AppData\Local\Xamarin\Xamarin.Android.Support.v7.CardView\23.3.0.0\content\./ doesn't exist.
...
Please install package: 'Xamarin.Android.Support.Vector.Drawable' available in SDK installer. Java library file C:\Users\***\AppData\Local\Xamarin\Xamarin.Android.Support.Vector.Drawable\23.3.0.0\content\classes.jar doesn't exist.
...
Please install package: 'Xamarin.Android.Support.v4' available in SDK installer. Android resource directory C:\Users\***\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.3.0.0\content\./ doesn't exist.

... and so on.

I installed these packages manually from the nuget server, but the error messages are still generated ...
Why are these packages reported as missing, respectively why are they searched into the c:\users\... folder ?

**Comment by awcullen** [comment]
I am just learning about Xamarin as well.
To get the SDK for Xamarin Android support, I chose Tools...Android...Android SDK Manager.
Then I installed the following items: 
![2016-12-22](https://cloud.githubusercontent.com/assets/11900570/21430600/db683874-c831-11e6-9549-d46a5af12314.png)

**Comment by awcullen** [comment]
Next I created an Android Virtual Device (emulator).
I chose Tools...Android...Android Emulator Manager:
![2016-12-22 2](https://cloud.githubusercontent.com/assets/11900570/21430997/851e9952-c833-11e6-8fde-3bea9b976e2e.png)

I selected the Nexus 4 by Google and clicked Create AVD...
 
I filled out the form as shown:
![2016-12-22 1](https://cloud.githubusercontent.com/assets/11900570/21430875/07e920b0-c833-11e6-85ae-931ead60a6cd.png)

**Comment by abrasat** [comment]
After downlaoding the OPC-UA samples and trying to compile it with VS 2015, the following errors occur:
...
The package Microsoft.CSharp with version 4.0.1 could not be found in C:\Users\Andrew\.nuget\packages\. Run a NuGet package restore to download the package.	Workstation.Common.Uwp			
...
Your project is not referencing the "MonoAndroid,Version=v6.0" framework. Add a reference to "MonoAndroid,Version=v6.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.	Workstation.MobileHmi.Droid			
...

The project.json file in the "Workstation.Common.Uwp" project seems to contain some references to directories from your development environment ("C:\Users\Andrew\...").

In the project.json file from the "Workstation.MobileHmi.Droid" project seems that some references (MonoAndroid) are missing.

**Comment by awcullen** [comment]
To help fix the first part of the question:
I removed the project.lock.json from the repo. This file is recreated if necessary when the project is rebuilt.
I lowerer the target Android API to 23 and MonoAndroid to v6.0, which are more commonly installed. 

Regarding the last Xamarin Forms error:
Please check the properties of the MainPage.xaml in the shared project. Then restart Visual Studio.
![2017-01-06](https://cloud.githubusercontent.com/assets/11900570/21723242/b70341fe-d3fd-11e6-9c96-06ee6eb340d1.png)

**Comment by abrasat** [comment]
Thanks, I will look into that, but probably first in a couple of days.
Do you have the RobotHmi sample also as a Xamarin/Android version ? If yes, could you please add it to the repository of samples?

**Comment by awcullen** [comment]
I'm working on it. https://urho3d.github.io/
